# Generated by Django 5.2.6 on 2025-09-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
