# Generated by Django 5.0.2 on 2025-09-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
