# Generated by Django 5.0.2 on 2025-09-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_update_at_ingredient_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
