# Generated by Django 5.2.6 on 2026-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
